{"time":"2024-06-06 12:22:44","level":"INFO","module":"__init__","method":"setup","line":464,"path":"\/Users\/vasamsettyvenkatasaikushank\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-06-06 12:23:11","level":"INFO","module":"__init__","method":"setup","line":464,"path":"\/Users\/vasamsettyvenkatasaikushank\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-06-06 12:44:02","level":"INFO","module":"__init__","method":"setup","line":464,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-06-06 12:44:08","level":"INFO","module":"__init__","method":"setup","line":464,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-06-06 12:44:28","level":"INFO","module":"__init__","method":"setup","line":464,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-06-06 12:51:28","level":"ERROR","module":"__init__","method":"global_exception_logger","line":20,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"byte indices must be integers or slices, not str","exception":"Traceback (most recent call last):\n  File \"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/api\/anaconda_api.py\", line 242, in _load_unsafe_channels\n    new_worker.unsafe_channels = info['channels']\n                                 ~~~~^^^^^^^^^^^^\nTypeError: byte indices must be integers or slices, not str"}
{"time":"2024-06-06 12:51:28","level":"ERROR","module":"__init__","method":"global_exception_logger","line":20,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"'ProcessWorker' object has no attribute 'base_worker'","exception":"Traceback (most recent call last):\n  File \"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/api\/anaconda_api.py\", line 246, in _conda_info_processed\n    base_worker = worker.base_worker\n                  ^^^^^^^^^^^^^^^^^^\nAttributeError: 'ProcessWorker' object has no attribute 'base_worker'"}
{"time":"2024-06-06 12:51:32","level":"ERROR","module":"__init__","method":"global_exception_logger","line":20,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"byte indices must be integers or slices, not str","exception":"Traceback (most recent call last):\n  File \"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/api\/anaconda_api.py\", line 242, in _load_unsafe_channels\n    new_worker.unsafe_channels = info['channels']\n                                 ~~~~^^^^^^^^^^^^\nTypeError: byte indices must be integers or slices, not str"}
{"time":"2024-06-06 12:51:32","level":"ERROR","module":"__init__","method":"global_exception_logger","line":20,"path":"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"'ProcessWorker' object has no attribute 'base_worker'","exception":"Traceback (most recent call last):\n  File \"\/opt\/anaconda3\/lib\/python3.11\/site-packages\/anaconda_navigator\/api\/anaconda_api.py\", line 246, in _conda_info_processed\n    base_worker = worker.base_worker\n                  ^^^^^^^^^^^^^^^^^^\nAttributeError: 'ProcessWorker' object has no attribute 'base_worker'"}
